export const PHYSICS = {
  FRICCION: 0.03,
  FRICCION_PELOTA: 0.01,
  PERDIDA_COLISION: 0.05,
  COEF_RESTITUCION: 0.7,
  UMBRAL_DETENIDO: 0.001,
  STEAL_FRONT_ANGLE: 1.2
}

export const POWER = {
  V_MAX_CAMPO: 0.63,
  V_MAX_ARQUERO: 0.63,
  KICK_RATIO_CAMPO: 1.0,
  KICK_RATIO_ARQUERO: 1.3
}

export const PITCH_BASE = {
  GOAL_TO_GOAL: 100,
  WIDTH: 64,
  GOAL_WIDTH: 7.32,
  GOAL_DEPTH: 2.44,
  GOAL_AREA_DEPTH: 5.5,
  GOAL_AREA_WIDTH: 18.32,
  CENTER_CIRCLE_RADIUS: 9.15,
  BALL_RADIUS: 0.6,
  DISK_RADIUS: 1.8,
  MARGIN: 0.04
}

export const ENTITIES = {
  JUGADORES_POR_EQUIPO: 11,
  ARQUEROS: 1
}

export const COLORS = {
  PITCH_GREEN: 0x269b5a,
  PITCH_LINE: 0xfffbf0,
  BALL: 0xfff8d6,
  TEAM_ROJO: 0xff4355,
  TEAM_ROJO_SELECTED: 0xff8e8e,
  TEAM_AZUL: 0x3e8dff,
  TEAM_AZUL_SELECTED: 0x95d2ff,
  GOAL: 0xfff5dd,
  DIRECTION_LINE: 0xfffbf0,
  POWER_BAR: 0xffc533
}

export const TEAMS = {
  ROJO: 'rojo',
  AZUL: 'azul'
}
